name = "pressprotocol-api"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
IPFS_GATEWAY_URL = "https://ipfs.filebase.io/ipfs"
CORS_ORIGIN = "*"
ENVIRONMENT = "production"
PUBLIC_APP_URL = "https://pressprotocol.com"
TOR_ONION_GATEWAY = "pressprotocol7sovereign4node6federation3mesh7relay5v3.onion"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
